# Generated by Django 4.0.3 on 2022-03-18 14:30
from django.db import migrations


class Migration(migrations.Migration):
    def create_group(apps, schema_migration):
        User = apps.get_model("auth", "User")
        Group = apps.get_model("auth", "Group")
        Permission = apps.get_model("auth", "Permission")

        can_vote = Permission.objects.get(codename="can_vote")

        customers_permissions = [can_vote]

        customers = Group(name="customers")
        customers.save()
        customers.permissions.set(customers_permissions)

        for user in User.objects.filter(is_superuser=False):
            customers.user_set.add(user)

    dependencies = []

    operations = [migrations.RunPython(create_group)]
