# Generated by Django 4.0.3 on 2022-03-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0006_alter_artwork_description_alter_artwork_height_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="artwork",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
