# Generated by Django 4.0.3 on 2022-03-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0009_alter_artwork_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='api_fetched',
            field=models.BooleanField(default=False),
        ),
    ]
