# Generated by Django 4.0.3 on 2022-03-18 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0008_artwork_votes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="artwork",
            options={"permissions": (("can_vote", "Can vote for an artwork"),)},
        ),
    ]
