# Generated by Django 4.0.3 on 2022-03-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0010_artwork_api_fetched"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artwork",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="artwork",
            unique_together={("title", "artist")},
        ),
    ]
