# Generated by Django 4.0.3 on 2022-03-31 21:38

from django.db import migrations

from artworks.models import Category


def add_categories(apps, schema_editor):
    Category = apps.get_model("artworks", "Category")

    Category.objects.create(name="Peinture à l'huile")
    Category.objects.create(name="Sculpture")
    Category.objects.create(name="Peinture à l'eau")
    Category.objects.create(name="Gravure")
    Category.objects.create(name="Tapisserie")
    Category.objects.create(name="Mosaïque")
    Category.objects.create(name="Vitraux")
    Category.objects.create(name="Collage")


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0011_alter_artwork_title_alter_artwork_unique_together"),
    ]

    operations = [
        migrations.RunPython(add_categories),
    ]
